# Generated by Django 4.0.2 on 2022-02-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0003_remove_tipoambiente_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(choices=[('UN', 'UNIDADE'), ('HR', 'HORA'), ('MT', 'METROS'), ('M2', 'METRO QUADRADO')], max_length=2)),
                ('risco', models.CharField(choices=[('A', 'ALTO'), ('M', 'MÉDIO'), ('B', 'BAIXO')], max_length=1)),
                ('observacao', models.TextField()),
                ('tipo_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.tipoambiente')),
            ],
        ),
    ]
