# Generated by Django 4.0.2 on 2022-02-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_remove_tipoambiente_area'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervico',
            name='tipo_ambiente',
        ),
        migrations.CreateModel(
            name='TipoAmbienteServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.tipoambiente')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.tiposervico')),
            ],
        ),
    ]
