# Generated by Django 4.0.2 on 2022-02-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_remove_tipoambiente_area'),
        ('servicos', '0002_remove_tiposervico_tipo_ambiente_tipoambienteservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='tipo_ambiente',
            field=models.ManyToManyField(to='entidades.TipoAmbiente'),
        ),
        migrations.DeleteModel(
            name='TipoAmbienteServico',
        ),
    ]
