# Generated by Django 4.0.2 on 2022-02-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_remove_tipoambiente_area'),
        ('servicos', '0003_tiposervico_tipo_ambiente_delete_tipoambienteservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.ambiente')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.tiposervico')),
            ],
        ),
    ]
