# Generated by Django 4.0.2 on 2022-02-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_remove_tipoambiente_area'),
        ('servicos', '0004_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='entidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='entidades.entidade'),
            preserve_default=False,
        ),
    ]
