# Generated by Django 4.0.2 on 2022-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servico_entidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='finalizado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
