# Generated by Django 4.0.2 on 2022-03-04 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_ambiente_entidade'),
        ('servicos', '0007_cadastrochecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('BOO', 'BOOLEAN')], max_length=3)),
                ('descricao', models.CharField(max_length=255)),
                ('obrigatorio', models.BooleanField()),
                ('publicado', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastrochecklist',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='entidade',
        ),
        migrations.AddField(
            model_name='cadastrochecklist',
            name='tipo_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicos.tiposervico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_execucao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_checklist', models.DateTimeField()),
                ('valor_item', models.BooleanField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('observacao', models.TextField(blank=True)),
                ('fim_checklist', models.DateTimeField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.ambiente')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.cadastrochecklist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.cadastroitemchecklist')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.servico')),
            ],
        ),
        migrations.AddField(
            model_name='cadastrochecklist',
            name='tipo_item',
            field=models.ManyToManyField(to='servicos.CadastroItemChecklist'),
        ),
    ]
