# Generated by Django 4.0.2 on 2022-03-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_cadastroitemchecklist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrochecklist',
            old_name='tipo_item',
            new_name='itens',
        ),
        migrations.AlterField(
            model_name='cadastroitemchecklist',
            name='publicado',
            field=models.BooleanField(),
        ),
    ]
