# Generated by Django 4.0.2 on 2022-04-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_tipoambiente_checklists_relacionados'),
        ('servicos', '0009_rename_tipo_item_cadastrochecklist_itens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='observacao',
        ),
        migrations.CreateModel(
            name='ChecklistPreenchido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', models.JSONField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.ambiente')),
            ],
        ),
    ]
