# Generated by Django 4.0.2 on 2022-04-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0010_remove_checklist_observacao_checklistpreenchido'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistpreenchido',
            name='checklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='servicos.checklist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistpreenchido',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='servicos.servico'),
            preserve_default=False,
        ),
    ]
