# Generated by Django 4.0.2 on 2022-04-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0011_checklistpreenchido_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistpreenchido',
            name='foto_checklist_antes',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistpreenchido',
            name='foto_checklist_depois',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
