# Generated by Django 4.0.2 on 2022-04-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0012_checklistpreenchido_foto_checklist_antes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistpreenchido',
            name='foto_checklist_antes',
        ),
    ]
