# Generated by Django 4.0.2 on 2022-04-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0013_remove_checklistpreenchido_foto_checklist_antes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistpreenchido',
            name='servico',
        ),
        migrations.AlterField(
            model_name='checklistpreenchido',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.cadastrochecklist'),
        ),
    ]
