# Generated by Django 4.0.2 on 2022-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0014_remove_checklistpreenchido_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistpreenchido',
            name='data_hora',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
