# Generated by Django 4.0.2 on 2022-05-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0017_remove_cadastroitemchecklist_tipo_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistpreenchido',
            name='usuario',
        ),
    ]
