# Generated by Django 4.0.2 on 2022-02-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastrounico', '0006_remove_pessoa_enderecos_pessoa_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao', models.CharField(max_length=255, verbose_name='Nome/Razão')),
                ('tipo_entidade', models.CharField(choices=[('G', 'Governo'), ('A', 'Autarquia'), ('P', 'Privada'), ('M', 'Mista')], max_length=1)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastrounico.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('risco', models.CharField(choices=[('A', 'ALTO'), ('M', 'MÉDIO'), ('B', 'BAIXO')], max_length=1)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('controla_checklist', models.BooleanField(default=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.entidade')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.entidade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastrounico.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('ano', models.CharField(max_length=4)),
                ('data_validade', models.DateField()),
                ('prorrogavel', models.BooleanField()),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacao', models.TextField()),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.entidade')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('andar', models.CharField(blank=True, max_length=20)),
                ('bloco', models.CharField(blank=True, max_length=20)),
                ('tipo_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.tipoambiente')),
            ],
        ),
    ]
