# Generated by Django 4.0.2 on 2022-02-25 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrounico', '0006_remove_pessoa_enderecos_pessoa_cidade_and_more'),
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastrounico.pessoa'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='nome_razao',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome/Razão'),
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
