# Generated by Django 4.0.2 on 2022-02-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_contrato_responsavel_alter_entidade_nome_razao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoambiente',
            name='area',
        ),
    ]
