# Generated by Django 4.0.2 on 2022-03-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_ambiente_entidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoambiente',
            name='entidade',
        ),
    ]
