# Generated by Django 4.0.2 on 2022-06-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_tipoambiente_checklists_relacionados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoambiente',
            name='checklists_relacionados',
        ),
    ]
