# Generated by Django 4.0.2 on 2022-06-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0019_checklistpreenchido_usuario'),
        ('entidades', '0008_remove_tipoambiente_checklists_relacionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoambiente',
            name='checklists_relacionados',
            field=models.ManyToManyField(to='servicos.CadastroChecklist'),
        ),
    ]
