# Generated by Django 4.0.2 on 2022-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrounico', '0004_enderecopessoa_tipo_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecopessoa',
            name='tipo_endereco',
            field=models.CharField(choices=[('COMERCIAL', 'COMERCIAL'), ('RESIDENCIAL', 'RESIDENCIAL'), ('OUTROS', 'OUTROS')], max_length=11),
        ),
    ]
