# Generated by Django 4.0.2 on 2022-03-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrounico', '0006_remove_pessoa_enderecos_pessoa_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='codigo_ibge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
